//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplyMainEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int CourseID { get; set; }
        public int RoomID { get; set; }
        public string RoomLocation { get; set; }
        public string BuildingName { get; set; }
        public Nullable<short> RoomCap { get; set; }
    }
}
