//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplyMainEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeBlock
    {
        public int CourseID { get; set; }
        public byte Day_ { get; set; }
        public Nullable<short> StartTime { get; set; }
        public Nullable<short> EndTime { get; set; }
        public Nullable<short> TermID { get; set; }
        public Nullable<int> RoomID { get; set; }
    
        public virtual DayTable DayTable { get; set; }
    }
}
